on:
  push:
  pull_request:
  schedule:
    - cron: '30 13 * * *'
permissions: { }
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - 'ubuntu-22.04'
          - 'ubuntu-22.04-arm'
          - 'macos-15'
          - 'macos-15-intel'
          - 'windows-2022'
          - 'windows-11-arm'
        py:
          - '3.12'
          - '3.13'
          - '3.13t'
          - '3.14'
          - '3.14t'
        arch:
          - 'arm64'
          - 'x64'
        exclude:
          - os: 'ubuntu-22.04'
            arch: 'arm64'
          - os: 'ubuntu-22.04-arm'
            arch: 'x64'
          - os: 'macos-15'
            arch: 'x64'
          - os: 'macos-15-intel'
            arch: 'arm64'
          - os: 'windows-2022'
            arch: 'arm64'
          - os: 'windows-11-arm'
            arch: 'x64'

    runs-on: ${{ matrix.os }}
    env:
      # Enable fuzzing tests, other expensive tests.
      ZSTD_SLOW_TESTS: '1'
      # Make all compile warnings fatal.
      ZSTD_WARNINGS_AS_ERRORS: '1'
      # More thorough fuzzing coverage.
      HYPOTHESIS_PROFILE: 'ci'
      # Activate Python development mode so we get warnings.
      PYTHONDEVMODE: '1'
    steps:
      - name: Set up Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: ${{ matrix.py }}
          architecture: ${{ matrix.arch }}
          allow-prereleases: true

      - name: Install Rust
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # v1
        with:
          toolchain: stable

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@d9e0f98d3fc6adb07d1e3d37f3043649ddad06a1 # v6.5.0
        with:
          version: "0.8.11"

      - name: Test C Backend
        run: |
          uv -v run --locked pytest --numprocesses=auto --hypothesis-profile=${HYPOTHESIS_PROFILE} -v

      - name: Test Rust Backend
        # Rust backend is currently experimental. So ignore failures in it.
        continue-on-error: true
        env:
          HYPERLIGHT_ZSTANDARD_IMPORT_POLICY: 'rust'
        run: |
          # We need --reinstall to get uv to pick up the config settings change.
          # Unsure if this is a bug.
          uv -v run --locked --config-settings-package 'zstandard:--global-option=--rust-backend' --reinstall pytest --numprocesses=auto --hypothesis-profile=${HYPOTHESIS_PROFILE} -v
